version: '3'

services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=${MONGO_URI}
      - SECRET_KEY=${SECRET_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}  # Added Gemini API key
    volumes:
      - ./images:/app/images
      - ./processed_images:/app/processed_images
    # Using Python 3.11 as specified in the Dockerfile