name: Generate Stability API Keys

on:
  schedule:
    # Run every 15 minutes
    - cron: '*/15 * * * *'
  workflow_dispatch:  # Allow manual triggering

jobs:
  generate_api_key:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1  # Only fetch the latest commit
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget gnupg
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo gpg --dearmor -o /usr/share/keyrings/googlechrome-linux-keyring.gpg
          echo "deb [arch=amd64 signed-by=/usr/share/keyrings/googlechrome-linux-keyring.gpg] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          google-chrome --version  # Print Chrome version for debugging
      
      - name: Install ChromeDriver
        run: |
          CHROME_VERSION=$(google-chrome --version | awk '{print $3}' | cut -d. -f1)
          echo "Chrome major version: $CHROME_VERSION"
          wget -q "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION" -O LATEST_RELEASE
          CHROMEDRIVER_VERSION=$(cat LATEST_RELEASE)
          echo "Using ChromeDriver version: $CHROMEDRIVER_VERSION"
          wget -q "https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip"
          unzip chromedriver_linux64.zip
          chmod +x chromedriver
          sudo mv chromedriver /usr/local/bin/
          chromedriver --version  # Print ChromeDriver version for debugging
          rm LATEST_RELEASE chromedriver_linux64.zip
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Install specific Selenium dependencies first
          pip install selenium==4.16.0 webdriver-manager==4.0.1 pyperclip==1.8.2
          # Then install the rest of the requirements
          pip install -r Development/requirements.txt
          # List installed packages for debugging
          pip list
      
      - name: Verify directory structure
        run: |
          ls -la
          ls -la Development/
          ls -la Development/StabilityApiGenerator/
      
      - name: Set up environment variables
        run: |
          # Set MongoDB URI from secrets
          echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> $GITHUB_ENV
          # Check if MongoDB URI is set (without showing the value)
          if [ -n "${{ secrets.MONGO_URI }}" ]; then
            echo "MongoDB URI is set"
          else
            echo "MongoDB URI is NOT set"
          fi
      
      - name: Run StabilityApiGenerator
        id: run_generator
        continue-on-error: true  # Don't fail the whole job if this step fails
        run: |
          cd Development
          # Run with more verbose output
          python -u StabilityApiGenerator/stability_api_generator.py
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          PYTHONUNBUFFERED: 1
      
      - name: Check StabilityApiGenerator Result
        run: |
          if [ "${{ steps.run_generator.outcome }}" == "success" ]; then
            echo "✅ Successfully generated API key!"
          else
            echo "❌ Failed to generate API key. Check logs for details."
            exit 1  # Mark the job as failed
          fi
        
      - name: Check credits of generated keys
        if: steps.run_generator.outcome == 'success'
        run: |
          cd Development
          python test_stability_api_key.py --refresh
          
      - name: Upload logs
        if: always()  # Always run this step, even if previous steps failed
        uses: actions/upload-artifact@v3
        with:
          name: stability-generator-logs
          path: |
            Development/stability_generator.log
            Development/StabilityApiGenerator/*.log
            Development/StabilityApiGenerator/email_content.*
            Development/*.png
            Development/StabilityApiGenerator/*.png
          retention-days: 7 